#!/system/bin/sh

sleep 10s
chmod 644 /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
echo 'schedutil' > /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
chmod 444 /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
chmod 644 /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor
echo 'schedutil' > /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor
chmod 444 /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor
chmod 644 /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor
echo 'schedutil' > /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor
chmod 444 /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor
chmod 644 /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor
echo 'schedutil' > /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor
chmod 444 /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor
chmod 644 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 'schedutil' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
chmod 444 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
chmod 644 /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo 'schedutil' > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
chmod 444 /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
chmod 644 /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
echo 'schedutil' > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
chmod 444 /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
chmod 644 /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
echo 'schedutil' > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
chmod 444 /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor

#cpu online
chmod 644 /sys/bus/cpu/devices/cpu0/online
echo '1' > /sys/bus/cpu/devices/cpu0/online
chmod 444 /sys/bus/cpu/devices/cpu0/online
chmod 644 /sys/bus/cpu/devices/cpu1/online
echo '1' > /sys/bus/cpu/devices/cpu1/online
chmod 444 /sys/bus/cpu/devices/cpu1/online
chmod 644 /sys/bus/cpu/devices/cpu2/online
echo '1' > /sys/bus/cpu/devices/cpu2/online
chmod 444 /sys/bus/cpu/devices/cpu2/online
chmod 644 /sys/bus/cpu/devices/cpu3/online
echo '1' > /sys/bus/cpu/devices/cpu3/online
chmod 444 /sys/bus/cpu/devices/cpu3/online
chmod 644 /sys/bus/cpu/devices/cpu4/online
echo '1' > /sys/bus/cpu/devices/cpu4/online
chmod 444 /sys/bus/cpu/devices/cpu4/online
chmod 644 /sys/bus/cpu/devices/cpu5/online
echo '1' > /sys/bus/cpu/devices/cpu5/online
chmod 444 /sys/bus/cpu/devices/cpu5/online
chmod 644 /sys/bus/cpu/devices/cpu6/online
echo '1' > /sys/bus/cpu/devices/cpu6/online
chmod 444 /sys/bus/cpu/devices/cpu6/online
chmod 644 /sys/bus/cpu/devices/cpu7/online
echo '1' > /sys/bus/cpu/devices/cpu7/online
chmod 444 /sys/bus/cpu/devices/cpu7/online

#core set
chmod 644 /dev/cpuset/background/cpus
echo '0-3' > /dev/cpuset/background/cpus

chmod 644 /dev/cpuset/foreground/cpus
echo '0-7' > /dev/cpuset/foreground/cpus

chmod 644 /dev/cpuset/top-app/cpus
echo '0-7' > /dev/cpuset/top-app/cpus

chmod 644 /dev/cpuset/system-background/cpus
echo '0-3' > /dev/cpuset/system-background/cpus

chmod 644 /dev/cpuset/camera-daemon/cpus
echo '0-3' > /dev/cpuset/camera-daemon/cpus

#msm_thermal
echo 0 > /sys/module/msm_thermal/core_control/enabled
echo 0 > /sys/module/msm_thermal/vdd_restriction/enabled
echo 0 > /sys/module/msm_thermal/parameters/enabled
