#!/system/bin/sh

sleep 30
chmod 755 /sys/class/power_supply/battery/constant_charge_current_max
echo `expr 2000 * 1000` > /sys/class/power_supply/battery/constant_charge_current_max

chmod 755 /sys/class/power_supply/battery/input_current_max
echo `expr 2000 * 1000` > /sys/class/power_supply/battery/input_current_max

echo 2000 > /sys/module/dwc3_msm/parameters/dcp_max_current
echo 2000 > /sys/module/dwc3_msm/parameters/hvdcp_max_current
echo 2000 > /sys/module/qpnp_smbcharger/parameters/default_dcp_icl_ma
echo 2000 > /sys/module/qpnp_smbcharger/parameters/default_hvdcp3_icl_ma
echo 2000 > /sys/module/qpnp_smbcharger/parameters/default_hvdcp_icl_ma

echo '480' >/sys/class/power_supply/bms/temp_warm
echo '150' >/sys/class/power_supply/bms/temp_cool

echo '1' > /sys/kernel/fast_charge/force_fast_charge
